[package]
authors = ["The Rust Project Developers"]
name = "dustc_ast_pretty"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
dustc_span = { path = "../dustc_span" }
dustc_ast = { path = "../dustc_ast" }
