[package]
authors = ["The Rust Project Developers"]
name = "dustc_interface"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
libc = "0.2"
tracing = "0.1"
dustc-rayon-core = "0.3.1"
rayon = { version = "0.3.1", package = "dustc-rayon" }
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
dustc_ast = { path = "../dustc_ast" }
dustc_attr = { path = "../dustc_attr" }
dustc_builtin_macros = { path = "../dustc_builtin_macros" }
dustc_expand = { path = "../dustc_expand" }
dustc_parse = { path = "../dustc_parse" }
dustc_session = { path = "../dustc_session" }
dustc_span = { path = "../dustc_span" }
dustc_serialize = { path = "../dustc_serialize" }
dustc_middle = { path = "../dustc_middle" }
dustc_ast_lowering = { path = "../dustc_ast_lowering" }
dustc_ast_passes = { path = "../dustc_ast_passes" }
dustc_incremental = { path = "../dustc_incremental" }
dustc_traits = { path = "../dustc_traits" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_codegen_ssa = { path = "../dustc_codegen_ssa" }
dustc_symbol_mangling = { path = "../dustc_symbol_mangling" }
dustc_codegen_llvm = { path = "../dustc_codegen_llvm", optional = true }
dustc_hir = { path = "../dustc_hir" }
dustc_index = { path = "../dustc_index" }
dustc_metadata = { path = "../dustc_metadata" }
dustc_mir = { path = "../dustc_mir" }
dustc_mir_build = { path = "../dustc_mir_build" }
dustc_passes = { path = "../dustc_passes" }
dustc_typeck = { path = "../dustc_typeck" }
dustc_lint = { path = "../dustc_lint" }
dustc_errors = { path = "../dustc_errors" }
dustc_plugin_impl = { path = "../dustc_plugin_impl" }
dustc_privacy = { path = "../dustc_privacy" }
dustc_query_impl = { path = "../dustc_query_impl" }
dustc_resolve = { path = "../dustc_resolve" }
dustc_trait_selection = { path = "../dustc_trait_selection" }
dustc_ty_utils = { path = "../dustc_ty_utils" }
tempfile = "3.0.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["libloaderapi"] }

[dev-dependencies]
dustc_target = { path = "../dustc_target" }

[features]
llvm = ['dustc_codegen_llvm']
