[package]
authors = ["The Rust Project Developers"]
name = "dustc_target"
version = "0.0.0"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
tracing = "0.1"
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_macros = { path = "../dustc_macros" }
dustc_serialize = { path = "../dustc_serialize" }
dustc_span = { path = "../dustc_span" }
dustc_index = { path = "../dustc_index" }
