[package]
authors = ["The Rust Project Developers"]
name = "dustc_symbol_mangling"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
punycode = "0.4.0"
dustc-demangle = "0.1.18"

dustc_ast = { path = "../dustc_ast" }
dustc_span = { path = "../dustc_span" }
dustc_middle = { path = "../dustc_middle" }
dustc_hir = { path = "../dustc_hir" }
dustc_target = { path = "../dustc_target" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_session = { path = "../dustc_session" }
