[package]
authors = ["The Rust Project Developers"]
name = "dustc_feature"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_span = { path = "../dustc_span" }
