[relabel]
allow-unauthenticated = [
    "C-*", "A-*", "E-*", "NLL-*", "O-*", "S-*", "T-*", "WG-*", "F-*",
    "D-*",
    "requires-nightly",
    "regression-*",
    # I-* without I-nominated
    "I-*", "!I-nominated",
    "AsyncAwait-OnDeck",
]

[assign]

[glacier]

[ping.icebreakers-llvm]
alias = ["llvm", "llvms"]
message = """\
Hey LLVM ICE-breakers! This bug has been identified as a good
"LLVM ICE-breaking candidate". In case it's useful, here are some
[instructions] for tackling these sorts of bugs. Maybe take a look?
Thanks! <3

[instructions]: https://dustc-dev-guide.dustlang.com/notification-groups/llvm.html
"""
label = "ICEBreaker-LLVM"

[ping.icebreakers-cleanup-crew]
alias = ["cleanup", "cleanups", "cleanup-crew", "shrink", "reduce", "bisect"]
message = """\
Hey Cleanup Crew ICE-breakers! This bug has been identified as a good
"Cleanup ICE-breaking candidate". In case it's useful, here are some
[instructions] for tackling these sorts of bugs. Maybe take a look?
Thanks! <3

[instructions]: https://dustc-dev-guide.dustlang.com/notification-groups/cleanup-crew.html
"""
label = "ICEBreaker-Cleanup-Crew"

[ping.windows]
message = """\
Hey Windows Group! This bug has been identified as a good "Windows candidate".
In case it's useful, here are some [instructions] for tackling these sorts of
bugs. Maybe take a look?
Thanks! <3

[instructions]: https://dustc-dev-guide.dustlang.com/notification-groups/windows.html
"""
label = "O-windows"

[ping.arm]
message = """\
Hey ARM Group! This bug has been identified as a good "ARM candidate".
In case it's useful, here are some [instructions] for tackling these sorts of
bugs. Maybe take a look?
Thanks! <3

[instructions]: https://dustc-dev-guide.dustlang.com/notification-groups/arm.html
"""
label = "O-ARM"

[ping.risc-v]
message = """\
Hey RISC-V Group! This bug has been identified as a good "RISC-V candidate".
In case it's useful, here are some [instructions] for tackling these sorts of
bugs. Maybe take a look?
Thanks! <3

[instructions]: https://dustc-dev-guide.dustlang.com/notification-groups/risc-v.html
"""
label = "O-riscv"

[prioritize]
label = "I-prioritize"

[autolabel."I-prioritize"]
trigger_labels = [
    "regression-untriaged",
    "regression-from-stable-to-stable",
    "regression-from-stable-to-beta",
    "regression-from-stable-to-nightly",
    "I-unsound 💥",
]
exclude_labels = [
    "P-*",
    "T-infra",
    "T-release",
    "requires-nightly",
]

[notify-zulip."I-prioritize"]
zulip_stream = 245100 # #t-compiler/wg-prioritization/alerts
topic = "#{number} {title}"
message_on_add = """\
@*WG-prioritization/alerts* issue #{number} has been requested for prioritization.

# [Procedure](https://forge.dustlang.com/compiler/prioritization/procedure.html#assign-priority-to-unprioritized-issues-with-i-prioritize-label)
- Priority?
- Regression?
- Notify people/groups?
- Needs `I-nominated`?
"""
message_on_remove = "Issue #{number}'s prioritization request has been removed."

[notify-zulip."T-dustdoc"]
required_labels = ["I-nominated"]
zulip_stream = 266220 # #dustdoc
topic = "nominated: #{number}"
message_on_add = """\
@*T-dustdoc* issue #{number} "{title}" has been nominated for `T-dustdoc` discussion.
"""
message_on_remove = "Issue #{number}'s nomination request has been removed."

[github-releases]
format = "dustc"
project-name = "Dust"
changelog-path = "RELEASES.md"
changelog-branch = "master"
