[package]
authors = ["The Rust Project Developers"]
name = "dustc_parse"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
bitflags = "1.0"
tracing = "0.1"
dustc_ast_pretty = { path = "../dustc_ast_pretty" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_feature = { path = "../dustc_feature" }
dustc_lexer = { path = "../dustc_lexer" }
dustc_errors = { path = "../dustc_errors" }
dustc_session = { path = "../dustc_session" }
dustc_span = { path = "../dustc_span" }
dustc_ast = { path = "../dustc_ast" }
unicode-normalization = "0.1.11"
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
