[package]
authors = ["The Dust Project Developers"]
name = "dustc_apfloat"
version = "0.0.0"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
