[package]
authors = ["The Rust Project Developers"]
name = "dustc_span"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_serialize = { path = "../dustc_serialize" }
dustc_macros = { path = "../dustc_macros" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_index = { path = "../dustc_index" }
dustc_arena = { path = "../dustc_arena" }
scoped-tls = "1.0"
unicode-width = "0.1.4"
cfg-if = "0.1.2"
tracing = "0.1"
sha-1 = "0.9"
sha2 = "0.9"
md-5 = "0.9"
