[package]
authors = ["The Rust Project Developers"]
name = "dustc_parse_format"
version = "0.0.0"
edition = "2018"

[dependencies]
dustc_span = { path = "../dustc_span" }
dustc_lexer = { path = "../dustc_lexer" }
