[package]
authors = ["The Rust Project Developers"]
name = "dustc_errors"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
dustc_serialize = { path = "../dustc_serialize" }
dustc_span = { path = "../dustc_span" }
dustc_macros = { path = "../dustc_macros" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_lint_defs = { path = "../dustc_lint_defs" }
unicode-width = "0.1.4"
atty = "0.2"
termcolor = "1.0"
annotate-snippets = "0.8.0"
termize = "0.1.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["handleapi", "synchapi", "winbase"] }
