blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://users.dustlang.com
    about: Please ask and answer questions about Dust on the user forum.
  - name: Feature Request
    url: https://internals.dustlang.com/
    about: Please discuss language feature requests on the internals forum.
