[package]
authors = ["The Rust Project Developers"]
name = "dustc_serialize"
version = "0.0.0"
edition = "2018"

[dependencies]
indexmap = "1"
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }

[dev-dependencies]
dustc_macros = { path = "../dustc_macros" }
