[package]
authors = ["The Rust Project Developers"]
name = "dustc_resolve"
version = "0.0.0"
edition = "2018"

[lib]
test = false
doctest = false

[dependencies]
bitflags = "1.2.1"
tracing = "0.1"
dustc_ast = { path = "../dustc_ast" }
dustc_arena = { path = "../dustc_arena" }
dustc_middle = { path = "../dustc_middle" }
dustc_ast_lowering = { path = "../dustc_ast_lowering" }
dustc_ast_pretty = { path = "../dustc_ast_pretty" }
dustc_attr = { path = "../dustc_attr" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_errors = { path = "../dustc_errors" }
dustc_expand = { path = "../dustc_expand" }
dustc_feature = { path = "../dustc_feature" }
dustc_hir = { path = "../dustc_hir" }
dustc_index = { path = "../dustc_index" }
dustc_metadata = { path = "../dustc_metadata" }
dustc_session = { path = "../dustc_session" }
dustc_span = { path = "../dustc_span" }
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
