[package]
authors = ["The Rust Project Developers"]
name = "dustc_hir_pretty"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_ast_pretty = { path = "../dustc_ast_pretty" }
dustc_hir = { path = "../dustc_hir" }
dustc_target = { path = "../dustc_target" }
dustc_span = { path = "../dustc_span" }
dustc_ast = { path = "../dustc_ast" }
