[package]
authors = ["The Rust Project Developers"]
name = "dustc_plugin_impl"
version = "0.0.0"
build = false
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_middle = { path = "../dustc_middle" }
dustc_errors = { path = "../dustc_errors" }
dustc_hir = { path = "../dustc_hir" }
dustc_lint = { path = "../dustc_lint" }
dustc_metadata = { path = "../dustc_metadata" }
dustc_ast = { path = "../dustc_ast" }
dustc_session = { path = "../dustc_session" }
dustc_span = { path = "../dustc_span" }
