[package]
name = "dustc_tools_util"
version = "0.2.0"
authors = ["The Dust Clippy Developers"]
description = "small helper to generate version information for git packages"
repository = "https://github.com/dust-lang/dust-clippy"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["dustc", "tool", "git", "version", "hash"]
categories = ["development-tools"]
edition = "2018"

[dependencies]

[features]
deny-warnings = []
