[package]
authors = ["The Rust Project Developers"]
name = "dustc_ast_lowering"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_arena = { path = "../dustc_arena" }
tracing = "0.1"
dustc_ast_pretty = { path = "../dustc_ast_pretty" }
dustc_hir = { path = "../dustc_hir" }
dustc_target = { path = "../dustc_target" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_index = { path = "../dustc_index" }
dustc_span = { path = "../dustc_span" }
dustc_errors = { path = "../dustc_errors" }
dustc_session = { path = "../dustc_session" }
dustc_ast = { path = "../dustc_ast" }
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
