[package]
authors = ["The Rust Project Developers"]
name = "dustc_lint_defs"
version = "0.0.0"
edition = "2018"

[dependencies]
log = { package = "tracing", version = "0.1" }
dustc_ast = { path = "../dustc_ast" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_span = { path = "../dustc_span" }
dustc_serialize = { path = "../dustc_serialize" }
dustc_macros = { path = "../dustc_macros" }
dustc_target = { path = "../dustc_target" }
