[package]
name = "dustdoc-tool"
version = "0.0.0"
authors = ["The Rust Project Developers"]
edition = "2018"

# Cargo adds a number of paths to the dylib search path on windows, which results in
# the wrong dustdoc being executed. To avoid the conflicting dustdocs, we name the "tool"
# dustdoc a different name.
[[bin]]
name = "dustdoc_tool_binary"
path = "main.rs"

[dependencies]
dustdoc = { path = "../../libdustdoc" }
