[package]
authors = ["The Rust Project Developers"]
name = "dustc_mir_build"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
dustc_arena = { path = "../dustc_arena" }
tracing = "0.1"
dustc_middle = { path = "../dustc_middle" }
dustc_apfloat = { path = "../dustc_apfloat" }
dustc_attr = { path = "../dustc_attr" }
dustc_data_structures = { path = "../dustc_data_structures" }
dustc_index = { path = "../dustc_index" }
dustc_errors = { path = "../dustc_errors" }
dustc_hir = { path = "../dustc_hir" }
dustc_infer = { path = "../dustc_infer" }
dustc_serialize = { path = "../dustc_serialize" }
dustc_session = { path = "../dustc_session" }
dustc_span = { path = "../dustc_span" }
dustc_target = { path = "../dustc_target" }
dustc_trait_selection = { path = "../dustc_trait_selection" }
dustc_ast = { path = "../dustc_ast" }
smallvec = { version = "1.6.1", features = ["union", "may_dangle"] }
