[package]
authors = ["The Rust Project Developers"]
name = "dust-demangler"
version = "0.0.1"
edition = "2018"

[dependencies]
regex = "1.0"
dustc-demangle = "0.1.17"

[[bin]]
name = "dust-demangler"
path = "main.rs"
