[package]
authors = ["The Dust Project Developers"]
name = "dustc-main"
version = "0.0.0"
edition = '2018'

[dependencies]
dustc_driver = { path = "../dustc_driver" }

# Make sure dustc_codegen_ssa ends up in the sysroot, because this
# box is intended to be used by codegen backends, which may not be in-tree.
dustc_codegen_ssa = { path = "../dustc_codegen_ssa" }

[dependencies.jemalloc-sys]
version = '0.3.0'
optional = true
features = ['unprefixed_malloc_on_supported_platforms']

[features]
jemalloc = ['jemalloc-sys']
llvm = ['dustc_driver/llvm']
max_level_info = ['dustc_driver/max_level_info']
