[book]
authors = ["The Rust Project Developers"]
multilingual = false
src = "src"
title = "The dustc book"

[output.html]
git-repository-url = "https://github.com/dust-lang/dust/tree/master/src/doc/dustc"
